import { JSONSchema7 } from "json-schema";
import { XSkyDialogue } from "../dialogue";
import Context from "../context";
import { sub } from "../../common/utils";
import { TOOL_NAME as task_planner } from "./task_planner";
import { DialogueTool, XSkyResult, ToolResult } from "../../types";

export const TOOL_NAME = "executeTask";

/**
 * A tool for executing a task.
 */
export default class ExecuteTaskTool implements DialogueTool {
  readonly name: string = TOOL_NAME;
  readonly description: string;
  readonly parameters: JSONSchema7;
  private xskyDialogue: XSkyDialogue;

  /**
   * Creates an instance of the ExecuteTaskTool.
   * @param xskyDialogue - The XSkyDialogue instance to use.
   */
  constructor(xskyDialogue: XSkyDialogue) {
    this.description = `Responsible for executing the task plan generated by the ${task_planner}. Use this tool if you need to execute planned tasks.`;
    this.parameters = {
      type: "object",
      properties: {
        taskId: {
          type: "string",
          description: `Task ID, generated by the \`${task_planner}\` tool.`,
        },
      },
      required: ["taskId"],
    };
    this.xskyDialogue = xskyDialogue;
  }

  /**
   * Executes the task.
   * @param args - The arguments for the tool.
   * @returns A promise that resolves to the result of the tool.
   */
  async execute(args: Record<string, unknown>): Promise<ToolResult> {
    const taskId = args.taskId as string;
    const xsky = this.xskyDialogue.getXSky(taskId);
    if (!xsky) {
      return {
        content: [
          {
            type: "text",
            text: "Error: Task ID not found.",
          },
        ],
      };
    }
    const result = await xsky.execute(taskId);
    const context = xsky.getTask(taskId);
    const variables = context?.variables;
    if (variables) {
      for (const key of variables.keys()) {
        this.xskyDialogue.getGlobalContext().set(key, variables.get(key));
      }
    }
    if (context) {
      return this.getTaskResult(context, result);
    } else {
      return {
        content: [
          {
            type: "text",
            text: result.result,
          },
        ],
      };
    }
  }

  private getTaskResult(context: Context, xskyResult: XSkyResult): ToolResult {
    let result =
      "# Task execution result\n" + JSON.stringify(xskyResult, null, 2);
    if (context.chain.agents.length > 1) {
      result += "\n\n## Subtask execution results";
      for (let i = 0; i < context.chain.agents.length; i++) {
        let agentChain = context.chain.agents[i];
        if (agentChain.agentResult) {
          const task = agentChain.agent.task || agentChain.agent.name;
          result += `\n### ${task}\n${sub(agentChain.agentResult, 800, true)}`;
        }
      }
    }
    return {
      content: [
        {
          type: "text",
          text: result,
        },
      ],
    };
  }
}

export { ExecuteTaskTool as DeepActionTool };
